# Generated by Django 3.2.7 on 2022-01-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lagos', '0002_auto_20211220_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ted',
            old_name='caption',
            new_name='category',
        ),
    ]
